# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
   # Enable version updates for actions
  - package-ecosystem: 'github-actions'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every week
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'github-actions'
    groups:
      all-in-one:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  
  # Enable version updates for npm packages (tfx-cli)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'npm'
  
  # Enable version updates for widget npm packages
  - package-ecosystem: 'npm'
    directory: '/widgets'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'npm'
  
  # Enable version updates for dependency review task npm packages
  - package-ecosystem: 'npm'
    directory: '/dependencyReviewTask'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'npm'
